# Generated by Django 5.1.1 on 2025-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("francais", models.FloatField()),
                ("histoire_geo", models.FloatField()),
                ("anglais", models.FloatField()),
                ("mathematiques", models.FloatField()),
                ("physique_chimie", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
